### PR TITLE
Use stable pyo3 v0.21.1 release

### PR DESCRIPTION
**Pull request by MarshalX**

### CODE REVIEW

**Comment by MarshalX** [comment]
who broke my project for the past 2 weeks 😢 let's compare the last successful run with the today`s one:
- 2 week old: https://github.com/MarshalX/python-libipld/actions/runs/8366643532/job/22907296322
- today: https://github.com/MarshalX/python-libipld/actions/runs/8507235248/job/23298745690

diff:
- pycparser 2.21 -> 2.22 (2.21 from 2021 and 2.22 from 2024)
- rust 1.76.0 - > 1.77.1
- maturin 1.5.0 -> 1.5.1

**Comment by MarshalX** [comment]
@davidhewitt fyi. some random segfault after upgrading to rust 1.17.1. idk is it on my side or pyo3`s. i think it could be related to https://blog.rust-lang.org/2024/03/30/i128-layout-update.html. for now, i will stay on rust 1.16.0. didn't expect it from rust...

**Comment by davidhewitt** [comment]
That's a concern. Are you able to identify what code is segfaulting, does it reproduce locally? We should understand if it's a PyO3 or Rust problem, and either way it's probably going to be classed as a regression from stable-to-stable worth a bugfix (unless it really is related to the i128 layout changes).

**Comment by MarshalX** [comment]
@davidhewitt I can't reproduce on `stable-x86_64-unknown-linux-gnu updated - rustc 1.77.1` 😢 i've tried 1:1 flow from CI. with PGO data gathering. exit code is always 0; tests are passed. i have no ideas...

**Comment by davidhewitt** [comment]
:(

Maybe can SSH into the runner and inspect the core dumps? See https://github.com/PyO3/pyo3/discussions/2781#discussioncomment-4228785 for ideas on how to do this.

**Comment by MarshalX** [comment]
@davidhewitt im sorry silly question what the difference between `pip install -v -e .` without installed rust toolchains with with? i mean unit test workflow passes and codspeed not. one calls just `pip install -v -e .` the another one uses `dtolnay/rust-toolchain` and then calls `pip install -v -e .`

**Comment by davidhewitt** [comment]
Yep preinstalled rust toolchain which is presumably older than 1.77 still.

**Comment by MarshalX** [comment]
@davidhewitt i ve had some success with CI debugging. here is what i got:

1. segfault happens with builds that were built with env var `RUSTFLAGS="-Cprofile-generate=profdata"`
2. 
image

**Comment by davidhewitt** [comment]
I think probably the best course of action here is to report this to the `rust-lang/rust` main repo, hopefully someone working on the compiler has ideas.

**Comment by MarshalX** [comment]
@davidhewitt I started to prepare issue and go to CI SSH once again to gather proper info about rustc version and... it passes! i just rerun failed workflow from yesterday https://github.com/MarshalX/python-libipld/pull/44. well... some temporary magic from GHA runners? or maybe they notices some crashes/issues and fixed already

**Comment by MarshalX** [comment]
but in this PR still fails. i can't take it anymore 😢 i will just sit and wait for some fix from GitHub

**Pull request closed without merging**
